# -*- python -*-

env = Environment(tools=['default', 'prefixoptions', 'vardb', 'netcdf', 'raf'])

env.Append(CXXFLAGS=Split("-Wall -g -O2 -Wno-write-strings"))
env.Append(LIBS=Split("Xm Xt X11 Xext"))

srcs = Split("vared.cc initv.cc Xwin.cc ccb.cc")

vared = env.Program("vared", srcs)

env.Default(vared)
env.Install(env['INSTALL_PREFIX']+'/bin', vared)

