# -*- python -*-

env = Environment(tools=['default', 'prefixoptions', 'vardb', 'vardbconverter'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))

vdbdump = env.Program("vdbdump.cc")

env.Default(vdbdump)
env.Install(env['INSTALL_PREFIX']+'/bin', vdbdump)

