# -*- python -*-

env = Environment(tools=['default', 'prefixoptions', 'vardb', 'vardbconverter'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))

vdbdump = env.Program("vdbdump.cc")

env.Default(vdbdump)

if env.get('INSTALL_VARDB') and env['INSTALL_VARDB'] == True:
  env.Install(env['INSTALL_PREFIX']+'/bin', vdbdump)
