# -*- python -*-

Import('PREFIX')

env = Environment(tools=['default', 'vardb'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))

vdbdump = env.Program("vdbdump.cc")

env.Default(vdbdump)
env.Install(PREFIX+'/bin', vdbdump)

