# -*- python -*-

Import('PREFIX')

env = Environment(tools=['default'])

modules = Split("""
addSignal.py
delete.py
generateButtons.py
getInfo.py
makeSingleRadioButton.py
newSignal.py
radioClickEvent.py
remove.py
setup.py
windowSetup.py
""")

# Targets are only to install files.
env.Install(PREFIX+'/bin', 'vdbEditor')
env.Install(PREFIX+'/lib/python/site-packages/vardb', modules)
