# -*- python -*-

env = Environment(tools=['default','prefixoptions'])

modules = Split("""
addSignal.py
delete.py
generateButtons.py
getInfo.py
makeSingleRadioButton.py
newSignal.py
radioClickEvent.py
remove.py
setup.py
windowSetup.py
""")

# Targets are only to install files.
if env.get('INSTALL_VARDB') and env['INSTALL_VARDB'] == True:
  env.Install(env['INSTALL_PREFIX']+'/bin', 'vdbEditor')
  env.Install(env['INSTALL_PREFIX']+'/lib/python/site-packages/vardb', modules)
