# -*- python -*-

env = Environment(tools=['default', 'vardb', 'netcdf','raf'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))

vdb2xml = env.Program("vdb2xml.cc")

env.Default(vdb2xml)
env.Install(env['INSTALL_PREFIX']+'/bin', vdb2xml)
