# -*- python -*-

env = Environment(tools=['default', 'vardb', 'netcdf'])

env.Append(CXXFLAGS=Split("-Wall -g -O2"))
env.Append(LIBS=['raf'])

vdb2xml = env.Program("vdb2xml.cc")

env.Default(vdb2xml)
env.Install(env['INSTALL_PREFIX']+'/bin', vdb2xml)
