# -*- python -*-

env = Environment(tools=['default', 'prefixoptions', 'vardb', 'vardbconverter'])

env.Append(CXXFLAGS=Split("-std=c++11 -Wall -g -O2"))

vdb2xml = env.Program("vdb2xml.cc")

env.Default(vdb2xml)
env.Install(env['INSTALL_PREFIX']+'/bin', vdb2xml)
