# -*- python -*-

env = Environment(tools=['default', 'vardb', 'testing', 'pylint',
                         'postgres_testdb', 'boost_python'])

module = env.SharedLibrary(env.File('vardb/_vardb.so'), ['src/vardb.cc'])
pysrcs = Split("vardb/__init__.py vardb/Variable.py")
tests = Split("vardb/test_vardb.py")

pg = env.PostgresTestDB()
sql = env.File("winter-real-time.sql.gz")

env.AppendENVPath('PYTHONPATH', env.Dir("#/../python").get_abspath())
env.AppendENVPath('PYTHONPATH', env.Dir('.').get_abspath())

env.PythonLint('lint', pysrcs,
               PYLINTPYTHONPATH=env['ENV']['PYTHONPATH'])

runtest = env.TestRun('pytests', tests+module+pysrcs+[sql],
                      [ pg.action_init,
                        "py.test ${SOURCE}",
                        pg.action_stop ])

# Do not run these tests by default until the module is built by default.
#
# env.DefaultTest(runtest)
